INSERT INTO TODO(ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE
) VALUES (10001, 'devjian', 'Get AWS Certified', CURRENT_DATE(), false);

INSERT INTO TODO(ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE
) VALUES (10002, 'jwkim', 'Get Azure Certified', CURRENT_DATE(), false);

INSERT INTO TODO(ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE
) VALUES (10003, 'devjian', 'Get GCP Certified', CURRENT_DATE(), false);

INSERT INTO TODO(ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE
) VALUES (10004, 'jwkim', 'Learn DevOps', CURRENT_DATE(), false);